name: JUnit

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  JUnit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Java with sdkman
        uses: sfesenko/setup-sdkman@v1
        with:
          deps: maven:3.9.8
                java:17.0.12-amzn
                kotlin:1.9.24
                kscript:4.2.3
      
      - name: Install LTSMin
        run: |
          wget https://github.com/Meijuh/ltsmin/releases/download/v3.1.0/ltsmin-v3.1.0-linux.tgz
          tar xvf ltsmin-v3.1.0-linux.tgz
          sudo cp -r v3.1.0/* /usr

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn dependency:go-offline --projects core

      - name: Test with Maven
        run: mvn test -DskipTests=False --projects core

      - name: Test a kscript example
        run: |
          kscript example/kotlin/mealy.main.kts

      #- name: Test a kscript example
      #  uses: plusmobileapps/kscript-action@v1.2
      #  with:
      #    kts-file: 'example/kotlin/mealy.main.kts'
      #    java-version: '17.0.12-amzn'
      #    kscript-version: '4.2.3'
      #    kotlin-version: '1.9.24'
      #    fail-on-failure: 'true'

      - name: Upload the test coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/my-reports
